# ============================================================
# Intern Mini Project
# Project : E-Commerce Order Analytics System
# Part 1 : Data Generation (Python)
#Skills Tested:
#Python
#SQL
#Problem Solving
# ============================================================

In [1]:
# ==========================================================
# Import Required Libraries
# ==========================================================

import pandas as pd
import sqlite3
import random
from random import randint, choice
from datetime import datetime, timedelta

In [2]:
# ==========================================================
# Create Project Folder (Optional)
# ==========================================================

import os

project_folder = "generated_data"

if not os.path.exists(project_folder):
    os.makedirs(project_folder)

print("Project Folder Ready")

Project Folder Ready

In [3]:
# ==========================================================
# Part 1 : Data Generation
#
# Generate customers.csv
# ==========================================================

customer_data = []

In [4]:
# ==========================================================
# Generate 500 Customers
# ==========================================================

customer_types = ["REGULAR", "PREMIUM", "VIP"]

first_names = [
    "Amit","Rahul","Priya","Sneha","Neha",
    "Rohan","Kiran","Pooja","Anjali","Vikas",
    "Tushar","Akash","Sagar","Nikita","Shubham"
]

last_names = [
    "Sharma","Patil","Verma","Gupta","Kumar",
    "Sontakke","Deshmukh","Jadhav","Joshi","Kulkarni"
]

In [5]:
# ==========================================================
# Create Customer Records
# ==========================================================

for i in range(1,501):

    customer_id = f"C{i:03d}"

    first = random.choice(first_names)
    last = random.choice(last_names)

    customer_name = first + " " + last

    email = first.lower() + str(i) + "@gmail.com"

    registration_date = (
        datetime(2023,1,1)
        + timedelta(days=random.randint(0,900))
    ).strftime("%Y-%m-%d")

    customer_type = random.choice(customer_types)

    customer_data.append([
        customer_id,
        customer_name,
        email,
        registration_date,
        customer_type
    ])

In [7]:
# ==========================================================
# Convert to DataFrame
# ==========================================================

customers = pd.DataFrame(
    customer_data,
    columns=[
        "customer_id",
        "customer_name",
        "email",
        "registration_date",
        "customer_type"
    ]
)

In [8]:
# ==========================================================
# Make 2% Emails Invalid
# (10 out of 500 Customers)
# ==========================================================

invalid_rows = random.sample(range(500),10)

for row in invalid_rows:

    customers.loc[row,"email"] = (
        customers.loc[row,"email"]
        .replace("@gmail.com","")
    )

In [9]:
# ==========================================================
# Display First 5 Customers
# ==========================================================

customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,C001,Shubham Verma,shubham1@gmail.com,2024-03-28,VIP
1,C002,Amit Joshi,amit2@gmail.com,2023-03-04,REGULAR
2,C003,Rahul Kumar,rahul3@gmail.com,2023-01-21,REGULAR
3,C004,Priya Patil,priya4@gmail.com,2023-10-18,PREMIUM
4,C005,Shubham Patil,shubham5@gmail.com,2024-09-07,REGULAR

In [10]:
# ==========================================================
# Save customers.csv
# ==========================================================

customers.to_csv(
    "generated_data/customers.csv",
    index=False
)

print("customers.csv generated successfully.")

customers.csv generated successfully.

In [11]:
# ==========================================================
# Generate products.csv
# ==========================================================

product_data = []

In [12]:
# ==========================================================
# Product Categories and Product Names
# ==========================================================

categories = [
    "Electronics",
    "Clothing",
    "Home",
    "Books"
]

electronics = [
    "Laptop",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Printer",
    "Speaker",
    "Headphone",
    "Camera"
]

clothing = [
    "T-Shirt",
    "Jeans",
    "Jacket",
    "Shirt",
    "Shoes",
    "Cap",
    "Sweater"
]

home = [
    "Chair",
    "Table",
    "Sofa",
    "Curtain",
    "Fan",
    "Bed",
    "Cupboard"
]

books = [
    "Python Book",
    "SQL Book",
    "Java Book",
    "AI Book",
    "Data Science Book",
    "C Programming Book"
]

In [13]:
# ==========================================================
# Generate 500 Products
# ==========================================================

for i in range(1,501):

    category = random.choice(categories)

    if category == "Electronics":
        product_name = random.choice(electronics)

    elif category == "Clothing":
        product_name = random.choice(clothing)

    elif category == "Home":
        product_name = random.choice(home)

    else:
        product_name = random.choice(books)

    price = round(random.uniform(100,50000),2)

    product_data.append([
        f"P{i:03d}",
        product_name,
        category,
        price
    ])

In [14]:
# ==========================================================
# Convert Product Data to DataFrame
# ==========================================================

products = pd.DataFrame(
    product_data,
    columns=[
        "product_id",
        "product_name",
        "category",
        "price"
    ]
)

In [15]:
# ==========================================================
# Add Mixed Case and Extra Spaces
# (Requirement from PDF)
# ==========================================================

rows = random.sample(range(500),20)

for row in rows:

    name = products.loc[row,"product_name"]

    products.loc[row,"product_name"] = "  " + name.upper() + "  "

In [16]:
# ==========================================================
# Display First 5 Products
# ==========================================================

products.head()

  product_id product_name     category     price
0       P001       Jacket     Clothing  38774.08
1       P002        Jeans     Clothing  39445.14
2       P003     Cupboard         Home  17520.45
3       P004       Camera  Electronics  20780.75
4       P005      Printer  Electronics  15197.37

In [17]:
# ==========================================================
# Save products.csv
# ==========================================================

products.to_csv(
    "generated_data/products.csv",
    index=False
)

print("products.csv generated successfully.")

products.csv generated successfully.

In [18]:
# ==========================================================
# Generate orders.csv
# ==========================================================

order_data = []

In [19]:
# ==========================================================
# Order Status List
# ==========================================================

order_status = [
    "PLACED",
    "SHIPPED",
    "DELIVERED",
    "CANCELLED",
    "RETURNED"
]

In [20]:
# ==========================================================
# Generate 500 Orders
# ==========================================================

for i in range(1,501):

    order_id = f"O{i:03d}"

    customer_id = f"C{random.randint(1,500):03d}"

    order_date = (
        datetime(2024,1,1)
        + timedelta(days=random.randint(0,730))
    )

    status = random.choice(order_status)

    region_code = random.choice([
        "NORTH",
        "SOUTH",
        "EAST",
        "WEST"
    ])

    order_data.append([
        order_id,
        customer_id,
        order_date.strftime("%Y-%m-%d %H:%M:%S"),
        status,
        region_code
    ])

In [21]:
# ==========================================================
# Convert Orders to DataFrame
# ==========================================================

orders = pd.DataFrame(
    order_data,
    columns=[
        "order_id",
        "customer_id",
        "order_date",
        "status",
        "region_code"
    ]
)

In [22]:
# ==========================================================
# Make 5% Customer IDs NULL
# ==========================================================

null_rows = random.sample(range(500),25)

for row in null_rows:

    orders.loc[row,"customer_id"] = None

In [23]:
# ==========================================================
# Change Some Dates to Wrong Format
# (DD-MM-YYYY)
# ==========================================================

wrong_date_rows = random.sample(range(500),20)

for row in wrong_date_rows:

    original = pd.to_datetime(
        orders.loc[row,"order_date"]
    )

    orders.loc[row,"order_date"] = original.strftime("%d-%m-%Y")

In [24]:
# ==========================================================
# Display First 5 Orders
# ==========================================================

orders.head()

  order_id customer_id           order_date     status region_code
0     O001        C280  2024-12-10 00:00:00    SHIPPED       SOUTH
1     O002        C010  2024-09-09 00:00:00  DELIVERED        EAST
2     O003        C067  2024-12-20 00:00:00  DELIVERED        EAST
3     O004        C035  2025-10-15 00:00:00   RETURNED        EAST
4     O005        C350  2025-08-03 00:00:00    SHIPPED       SOUTH

In [25]:
# ==========================================================
# Save orders.csv
# ==========================================================

orders.to_csv(
    "generated_data/orders.csv",
    index=False
)

print("orders.csv generated successfully.")

orders.csv generated successfully.

In [26]:
# ==========================================================
# Generate order_items.csv
# ==========================================================

order_item_data = []

In [27]:
# ==========================================================
# Generate 500 Order Items
# ==========================================================

for i in range(1,501):

    item_id = f"I{i:03d}"

    order_id = f"O{random.randint(1,500):03d}"

    product_id = f"P{random.randint(1,500):03d}"

    quantity = random.randint(1,10)

    unit_price = round(random.uniform(100,50000),2)

    discount_percent = random.choice([0,5,10,15,20,25,30,40,50])

    order_item_data.append([
        item_id,
        order_id,
        product_id,
        quantity,
        unit_price,
        discount_percent
    ])

In [28]:
# ==========================================================
# Convert Order Items to DataFrame
# ==========================================================

order_items = pd.DataFrame(
    order_item_data,
    columns=[
        "item_id",
        "order_id",
        "product_id",
        "quantity",
        "unit_price",
        "discount_percent"
    ]
)

In [29]:
# ==========================================================
# Make 3% Quantities Negative
# ==========================================================

negative_rows = random.sample(range(500),15)

for row in negative_rows:

    order_items.loc[row,"quantity"] = -random.randint(1,5)

In [30]:
# ==========================================================
# Display First 5 Order Items
# ==========================================================

order_items.head()

  item_id order_id product_id  quantity  unit_price  discount_percent
0    I001     O344       P204         3    22727.39                40
1    I002     O474       P281         8    26106.50                25
2    I003     O023       P263         7    27144.48                15
3    I004     O091       P491         8    10253.67                50
4    I005     O155       P393         7    18134.79                 0

In [31]:
# ==========================================================
# Save order_items.csv
# ==========================================================

order_items.to_csv(
    "generated_data/order_items.csv",
    index=False
)

print("order_items.csv generated successfully.")

order_items.csv generated successfully.

# ==========================================================
# PART 2 : DATA CLEANING
# ==========================================================

In [32]:
# ==========================================================
# Read Generated CSV Files
# ==========================================================

customers = pd.read_csv("generated_data/customers.csv")

products = pd.read_csv("generated_data/products.csv")

orders = pd.read_csv("generated_data/orders.csv")

order_items = pd.read_csv("generated_data/order_items.csv")

In [33]:
# ==========================================================
# Display Dataset Shapes
# ==========================================================

print("Customers :", customers.shape)

print("Products :", products.shape)

print("Orders :", orders.shape)

print("Order Items :", order_items.shape)

Customers : (500, 5)
Products : (500, 4)
Orders : (500, 5)
Order Items : (500, 6)

In [34]:
# ==========================================================
# Function : clean_orders()
# Purpose :
# 1. Fix wrong date formats
# 2. Handle NULL customer_id
# ==========================================================

def clean_orders(df):

    return df

In [35]:
# ==========================================================
# Fix Wrong Date Formats
# ==========================================================

def fix_date(date):

    try:
        return pd.to_datetime(date, format="%Y-%m-%d %H:%M:%S")

    except:

        try:
            return pd.to_datetime(date, format="%d-%m-%Y")

        except:
            return pd.NaT

In [36]:
# ==========================================================
# Apply Date Cleaning
# ==========================================================

orders["order_date"] = orders["order_date"].apply(fix_date)

In [37]:
# ==========================================================
# Handle NULL Customer IDs
# ==========================================================

orders["customer_id"] = orders["customer_id"].fillna("UNKNOWN")

In [38]:
# ==========================================================
# Return Cleaned Orders
# ==========================================================

def clean_orders(df):

    df["order_date"] = df["order_date"].apply(fix_date)

    df["customer_id"] = df["customer_id"].fillna("UNKNOWN")

    return df

In [39]:
# ==========================================================
# Execute clean_orders()
# ==========================================================

orders = clean_orders(orders)

orders.head()

  order_id customer_id order_date     status region_code
0     O001        C280 2024-12-10    SHIPPED       SOUTH
1     O002        C010 2024-09-09  DELIVERED        EAST
2     O003        C067 2024-12-20  DELIVERED        EAST
3     O004        C035 2025-10-15   RETURNED        EAST
4     O005        C350 2025-08-03    SHIPPED       SOUTH

# ==========================================================
# Function : clean_products()
#Purpose :
#Normalize Product Names
#1. Remove Extra Spaces
#2. Convert to Title Case
# ==========================================================

In [40]:
# ==========================================================
# Define clean_products() Function
# ==========================================================

def clean_products(df):

    df["product_name"] = (
        df["product_name"]
        .str.strip()
        .str.title()
    )

    return df

In [41]:
# ==========================================================
# Execute clean_products()
# ==========================================================

products = clean_products(products)

products.head()

  product_id product_name     category     price
0       P001       Jacket     Clothing  38774.08
1       P002        Jeans     Clothing  39445.14
2       P003     Cupboard         Home  17520.45
3       P004       Camera  Electronics  20780.75
4       P005      Printer  Electronics  15197.37

In [42]:
# ==========================================================
# Display Clean Product Names
# ==========================================================

products[["product_name"]].head(10)

  product_name
0       Jacket
1        Jeans
2     Cupboard
3       Camera
4      Printer
5      Ai Book
6    Java Book
7      Curtain
8        Jeans
9    Java Book

# ==========================================================
# Function : validate_emails()
#Purpose :
#Return Customer IDs Having Invalid Emails
# ==========================================================

In [43]:
# ==========================================================
# Define validate_emails() Function
# ==========================================================

def validate_emails(df):

    invalid = df[
        ~df["email"].str.contains("@", na=False)
    ]

    return invalid[["customer_id","email"]]

In [44]:
# ==========================================================
# Execute validate_emails()
# ==========================================================

invalid_emails = validate_emails(customers)

invalid_emails

    customer_id       email
80         C081     kiran81
124        C125    rahul125
174        C175    priya175
224        C225   nikita225
259        C260    rohan260
263        C264  shubham264
336        C337    akash337
382        C383    sneha383
437        C438    pooja438
498        C499    pooja499

# ==========================================================
# Function : check_referential_integrity()
#Purpose :
#Find Invalid Order References
# ==========================================================

In [45]:
# ==========================================================
# Define check_referential_integrity()
# ==========================================================

def check_referential_integrity(orders_df, items_df):

    invalid = items_df[
        ~items_df["order_id"].isin(orders_df["order_id"])
    ]

    return invalid

In [46]:
# ==========================================================
# Execute check_referential_integrity()
# ==========================================================

invalid_orders = check_referential_integrity(
    orders,
    order_items
)

invalid_orders

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [47]:
# ==========================================================
# Save Cleaned customers.csv
# ==========================================================

customers.to_csv(
    "generated_data/customers_cleaned.csv",
    index=False
)

print("customers_cleaned.csv saved successfully.")

customers_cleaned.csv saved successfully.

In [48]:
# ==========================================================
# Save Cleaned products.csv
# ==========================================================

products.to_csv(
    "generated_data/products_cleaned.csv",
    index=False
)

print("products_cleaned.csv saved successfully.")

products_cleaned.csv saved successfully.

In [49]:
# ==========================================================
# Save Cleaned orders.csv
# ==========================================================

orders.to_csv(
    "generated_data/orders_cleaned.csv",
    index=False
)

print("orders_cleaned.csv saved successfully.")

orders_cleaned.csv saved successfully.

In [50]:
# ==========================================================
# Save Cleaned order_items.csv
# ==========================================================

order_items.to_csv(
    "generated_data/order_items_cleaned.csv",
    index=False
)

print("order_items_cleaned.csv saved successfully.")

order_items_cleaned.csv saved successfully.

In [51]:

# ==========================================================
# Report : Invalid Emails
# ==========================================================

print("Invalid Emails Found :", len(invalid_emails))

invalid_emails

Invalid Emails Found : 10

    customer_id       email
80         C081     kiran81
124        C125    rahul125
174        C175    priya175
224        C225   nikita225
259        C260    rohan260
263        C264  shubham264
336        C337    akash337
382        C383    sneha383
437        C438    pooja438
498        C499    pooja499

In [52]:
# ==========================================================
# Report : Referential Integrity Issues
# ==========================================================

print("Invalid Order References :", len(invalid_orders))

invalid_orders

Invalid Order References : 0

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [53]:
# ==========================================================
# Data Cleaning Completed
# ==========================================================

print("Part 2 : Data Cleaning Completed Successfully")

Part 2 : Data Cleaning Completed Successfully

# ==========================================================
# PART 3 : SQL Analysis
# ==========================================================

In [54]:
# ==========================================================
# Create SQLite Database Connection
# ==========================================================

import sqlite3

connection = sqlite3.connect("ecommerce.db")

cursor = connection.cursor()

print("SQLite Database Connected Successfully")

SQLite Database Connected Successfully

In [55]:
# ==========================================================
# Load Cleaned CSV Files
# ==========================================================

customers = pd.read_csv("generated_data/customers_cleaned.csv")

products = pd.read_csv("generated_data/products_cleaned.csv")

orders = pd.read_csv("generated_data/orders_cleaned.csv")

order_items = pd.read_csv("generated_data/order_items_cleaned.csv")

In [56]:
# ==========================================================
# Store customers Table
# ==========================================================

customers.to_sql(
    "customers",
    connection,
    if_exists="replace",
    index=False
)

print("customers table created")

customers table created

In [57]:
# ==========================================================
# Store products Table
# ==========================================================

products.to_sql(
    "products",
    connection,
    if_exists="replace",
    index=False
)

print("products table created")

products table created

In [58]:
# ==========================================================
# Store orders Table
# ==========================================================

orders.to_sql(
    "orders",
    connection,
    if_exists="replace",
    index=False
)

print("orders table created")

orders table created

In [59]:
# ==========================================================
# Store order_items Table
# ==========================================================

order_items.to_sql(
    "order_items",
    connection,
    if_exists="replace",
    index=False
)

print("order_items table created")

order_items table created

In [60]:
# ==========================================================
# Verify Tables in SQLite Database
# ==========================================================

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

          name
0    customers
1     products
2       orders
3  order_items

In [61]:
# ==========================================================
# Display Customers Table
# ==========================================================

pd.read_sql(
    "SELECT * FROM customers LIMIT 5;",
    connection
)

,customer_id,customer_name,email,registration_date,customer_type
0,C001,Shubham Verma,shubham1@gmail.com,2024-03-28,VIP
1,C002,Amit Joshi,amit2@gmail.com,2023-03-04,REGULAR
2,C003,Rahul Kumar,rahul3@gmail.com,2023-01-21,REGULAR
3,C004,Priya Patil,priya4@gmail.com,2023-10-18,PREMIUM
4,C005,Shubham Patil,shubham5@gmail.com,2024-09-07,REGULAR

In [62]:
# ==========================================================
# Display Products Table
# ==========================================================

pd.read_sql(
    "SELECT * FROM products LIMIT 5;",
    connection
)

  product_id product_name     category     price
0       P001       Jacket     Clothing  38774.08
1       P002        Jeans     Clothing  39445.14
2       P003     Cupboard         Home  17520.45
3       P004       Camera  Electronics  20780.75
4       P005      Printer  Electronics  15197.37

In [63]:
# ==========================================================
# Display Orders Table
# ==========================================================

pd.read_sql(
    "SELECT * FROM orders LIMIT 5;",
    connection
)

  order_id customer_id  order_date     status region_code
0     O001        C280  2024-12-10    SHIPPED       SOUTH
1     O002        C010  2024-09-09  DELIVERED        EAST
2     O003        C067  2024-12-20  DELIVERED        EAST
3     O004        C035  2025-10-15   RETURNED        EAST
4     O005        C350  2025-08-03    SHIPPED       SOUTH

In [64]:
# ==========================================================
# Display Order Items Table
# ==========================================================

pd.read_sql(
    "SELECT * FROM order_items LIMIT 5;",
    connection
)

  item_id order_id product_id  quantity  unit_price  discount_percent
0    I001     O344       P204         3    22727.39                40
1    I002     O474       P281         8    26106.50                25
2    I003     O023       P263         7    27144.48                15
3    I004     O091       P491         8    10253.67                50
4    I005     O155       P393         7    18134.79                 0

In [65]:
# ==========================================================
# SQLite Database Ready
# ==========================================================

print("All Tables Loaded Successfully")

All Tables Loaded Successfully

In [66]:
# ==========================================================
# Query 1
# Total Revenue Per Category
# ==========================================================

query1 = """
SELECT
    p.category,
    ROUND(
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ),
        2
    ) AS total_revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;
"""

In [67]:
# ==========================================================
# Execute Query 1
# ==========================================================

pd.read_sql(query1, connection)

      category  total_revenue
0         Home    15107746.39
1  Electronics    14279919.99
2        Books    12897381.41
3     Clothing    10967863.26

In [68]:
# ==========================================================
# Query 2
# Top 10 Customers by Total Order Value
# ==========================================================

query2 = """
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent / 100.0)
        ),
        2
    ) AS total_order_value
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_order_value DESC
LIMIT 10;
"""

In [69]:
# ==========================================================
# Execute Query 2
# ==========================================================

pd.read_sql(query2, connection)

  customer_id   customer_name  total_order_value
0        C073     Sagar Joshi         1077862.98
1        C156    Anjali Gupta          794957.58
2        C355  Akash Deshmukh          737031.38
3        C283  Sneha Kulkarni          731842.40
4        C284     Rohan Kumar          672660.58
5        C064     Rahul Kumar          609555.78
6        C459  Rahul Deshmukh          592996.92
7        C101   Amit Kulkarni          589219.66
8        C098  Akash Kulkarni          576242.17
9        C177     Pooja Joshi          575686.33

In [70]:
# ==========================================================
# Query 3
# Month-wise Order Count
# ==========================================================

query3 = """
SELECT
    strftime('%Y-%m', order_date) AS month,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY month
ORDER BY month;
"""

In [71]:
# ==========================================================
# Execute Query 3
# ==========================================================

pd.read_sql(query3, connection)

      month  total_orders
0   2024-01            16
1   2024-02            14
2   2024-03            16
3   2024-04            18
4   2024-05            24
5   2024-06            21
6   2024-07            17
7   2024-08            19
8   2024-09            21
9   2024-10            24
10  2024-11            19
11  2024-12            17
12  2025-01            27
13  2025-02            17
14  2025-03            23
15  2025-04            22
16  2025-05            25
17  2025-06            25
18  2025-07            26
19  2025-08            27
20  2025-09            15
21  2025-10            26
22  2025-11            22
23  2025-12            19

In [72]:
# ==========================================================
# Query 4
# Find Customers Who Placed Orders But Never Had Any Item Delivered
# ==========================================================

query4 = """
SELECT DISTINCT
    c.customer_id,
    c.customer_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE c.customer_id NOT IN
(
    SELECT DISTINCT customer_id
    FROM orders
    WHERE status = 'DELIVERED'
);
"""

In [73]:
# ==========================================================
# Execute Query 4
# ==========================================================

pd.read_sql(query4, connection)

    customer_id   customer_name
0          C003     Rahul Kumar
1          C004     Priya Patil
2          C005   Shubham Patil
3          C006    Vikas Jadhav
4          C008  Vikas Deshmukh
..          ...             ...
229        C494    Sagar Jadhav
230        C495     Rahul Kumar
231        C497     Neha Sharma
232        C498    Sneha Sharma
233        C500  Kiran Sontakke

[234 rows x 2 columns]

In [74]:
# ==========================================================
# Query 5
# Products Ordered But Having More Returns Than Purchases
# ==========================================================

query5 = """
SELECT
    p.product_id,
    p.product_name,
    SUM(
        CASE
            WHEN oi.quantity > 0 THEN oi.quantity
            ELSE 0
        END
    ) AS purchased,

    ABS(
        SUM(
            CASE
                WHEN oi.quantity < 0 THEN oi.quantity
                ELSE 0
            END
        )
    ) AS returned

FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id

GROUP BY
    p.product_id,
    p.product_name

HAVING returned > purchased;
"""

In [75]:
# ==========================================================
# Execute Query 5
# ==========================================================

pd.read_sql(query5, connection)

  product_id       product_name  purchased  returned
0       P042             Jacket          0         3
1       P053  Data Science Book          0         1
2       P082                Bed          0         2
3       P284             Laptop          0         2

In [76]:
# ==========================================================
# Query 6
# Return Rate Per Category
# ==========================================================

query6 = """
SELECT

    p.category,

    ROUND(

        (
            SUM(
                CASE
                    WHEN oi.quantity < 0
                    THEN ABS(oi.quantity)
                    ELSE 0
                END
            ) * 100.0

        ) /

        SUM(ABS(oi.quantity))

    ,2)

    AS return_rate

FROM order_items oi

JOIN products p

ON oi.product_id = p.product_id

GROUP BY p.category;
"""

In [77]:
# ==========================================================
# Execute Query 6
# ==========================================================

pd.read_sql(query6, connection)

      category  return_rate
0        Books         2.01
1     Clothing         0.50
2  Electronics         1.10
3         Home         1.32

In [78]:
# ==========================================================
# Query 7
# Running Totals with Window Functions
# ==========================================================

query7 = """
SELECT
    o.region_code,
    DATE(o.order_date) AS order_date,

    ROUND(
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent/100.0)
        ),
        2
    ) AS daily_revenue,

    ROUND(
        SUM(
            SUM(
                oi.quantity *
                oi.unit_price *
                (1 - oi.discount_percent/100.0)
            )
        ) OVER(
            PARTITION BY o.region_code
            ORDER BY DATE(o.order_date)
        ),
        2
    ) AS running_total

FROM orders o

JOIN order_items oi
ON o.order_id = oi.order_id

GROUP BY
    o.region_code,
    DATE(o.order_date)

ORDER BY
    o.region_code,
    DATE(o.order_date);
"""

In [79]:
# ==========================================================
# Execute Query 7
# ==========================================================

pd.read_sql(query7, connection)

    region_code  order_date  daily_revenue  running_total
0          EAST  2024-01-01      -18532.84      -18532.84
1          EAST  2024-01-05       37770.82       19237.98
2          EAST  2024-01-10      224453.11      243691.09
3          EAST  2024-01-17      794957.58     1038648.67
4          EAST  2024-01-31      449316.07     1487964.74
..          ...         ...            ...            ...
294        WEST  2025-12-06      159356.23    10867026.45
295        WEST  2025-12-11       93693.24    10960719.69
296        WEST  2025-12-19      402603.99    11363323.68
297        WEST  2025-12-25      140863.46    11504187.14
298        WEST  2025-12-26       78388.80    11582575.94

[299 rows x 4 columns]

In [80]:
# ==========================================================
# Query 8
# Ranking with DENSE_RANK
# ==========================================================

query8 = """
SELECT

    p.category,

    p.product_name,

    ROUND(
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent/100.0)
        ),
        2
    ) AS total_revenue,

    DENSE_RANK() OVER(

        PARTITION BY p.category

        ORDER BY
        SUM(
            oi.quantity *
            oi.unit_price *
            (1 - oi.discount_percent/100.0)
        ) DESC

    ) AS rank_in_category

FROM products p

JOIN order_items oi

ON p.product_id = oi.product_id

GROUP BY
    p.category,
    p.product_name;
"""

In [81]:
# ==========================================================
# Execute Query 8
# ==========================================================

pd.read_sql(query8, connection)

       category        product_name  total_revenue  rank_in_category
0         Books            Sql Book     2797513.11                 1
1         Books  C Programming Book     2606976.85                 2
2         Books           Java Book     2246291.04                 3
3         Books         Python Book     2123659.94                 4
4         Books             Ai Book     1621263.25                 5
5         Books   Data Science Book     1501677.21                 6
6      Clothing               Jeans     3440845.04                 1
7      Clothing               Shoes     2234132.64                 2
8      Clothing               Shirt     1282295.44                 3
9      Clothing             T-Shirt     1196067.51                 4
10     Clothing              Jacket     1090431.22                 5
11     Clothing                 Cap      980458.22                 6
12     Clothing             Sweater      743633.18                 7
13  Electronics             Printer     3574745.25                 1
14  Electronics           Headphone     2442277.88                 2
15  Electronics             Monitor     2436988.97                 3
16  Electronics              Laptop     2297594.93                 4
17  Electronics               Mouse     1494375.04                 5
18  Electronics            Keyboard      911604.74                 6
19  Electronics             Speaker      709851.34                 7
20  Electronics              Camera      412481.83                 8
21         Home            Cupboard     3090117.88                 1
22         Home                Sofa     2976956.09                 2
23         Home             Curtain     2664967.65                 3
24         Home                 Bed     2478928.12                 4
25         Home               Chair     1637325.53                 5
26         Home                 Fan     1534144.14                 6
27         Home               Table      725306.97                 7

In [82]:
# ==========================================================
# Query 9
# LAG Analysis
# ==========================================================

query9 = """
SELECT

    customer_id,

    order_date,

    LAG(order_date)
    OVER(

        PARTITION BY customer_id

        ORDER BY order_date

    )

    AS previous_order_date,

    JULIANDAY(order_date)

    -

    JULIANDAY(

        LAG(order_date)
        OVER(
            PARTITION BY customer_id
            ORDER BY order_date
        )

    )

    AS days_gap

FROM orders

WHERE customer_id IS NOT NULL;
"""

In [83]:
# ==========================================================
# Execute Query 9
# ==========================================================

pd.read_sql(query9, connection)

    customer_id  order_date previous_order_date  days_gap
0          C003  2024-09-16                None       NaN
1          C004  2024-09-07                None       NaN
2          C005  2025-05-21                None       NaN
3          C006  2024-09-11                None       NaN
4          C006  2025-12-19          2024-09-11     464.0
..          ...         ...                 ...       ...
495     UNKNOWN  2025-09-14          2025-09-08       6.0
496     UNKNOWN  2025-09-15          2025-09-14       1.0
497     UNKNOWN  2025-10-25          2025-09-15      40.0
498     UNKNOWN  2025-12-25          2025-10-25      61.0
499     UNKNOWN  2025-12-27          2025-12-25       2.0

[500 rows x 4 columns]

In [84]:
# ==========================================================
# Query 10
# CTE with Multiple Levels
#
# Monthly Revenue Per Customer
# Categorize Customers:
# High (>10000)
# Medium (5000-10000)
# Low (<5000)
# ==========================================================

query10 = """
WITH monthly_revenue AS
(
    SELECT

        o.customer_id,

        strftime('%Y-%m',o.order_date) AS month,

        SUM(
            oi.quantity *
            oi.unit_price *
            (1-oi.discount_percent/100.0)
        ) AS revenue

    FROM orders o

    JOIN order_items oi
    ON o.order_id = oi.order_id

    WHERE o.customer_id IS NOT NULL

    GROUP BY
    o.customer_id,
    month
),

customer_category AS
(
    SELECT

        customer_id,

        month,

        revenue,

        CASE

            WHEN revenue > 10000 THEN 'High'

            WHEN revenue BETWEEN 5000 AND 10000 THEN 'Medium'

            ELSE 'Low'

        END AS customer_level

    FROM monthly_revenue
)

SELECT

    month,

    customer_level,

    COUNT(customer_id) AS total_customers

FROM customer_category

GROUP BY
month,
customer_level

ORDER BY
month,
customer_level;
"""

In [85]:
# ==========================================================
# Execute Query 10
# ==========================================================

pd.read_sql(query10, connection)

      month customer_level  total_customers
0   2024-01           High               12
1   2024-01            Low                1
2   2024-02           High                8
3   2024-02         Medium                1
4   2024-03           High                8
5   2024-04           High               12
6   2024-05           High               16
7   2024-05            Low                1
8   2024-05         Medium                1
9   2024-06           High               12
10  2024-07           High                8
11  2024-08           High                9
12  2024-08            Low                1
13  2024-09           High                9
14  2024-10           High               13
15  2024-10            Low                1
16  2024-11           High               11
17  2024-12           High               11
18  2024-12            Low                2
19  2025-01           High               15
20  2025-01         Medium                1
21  2025-02           High               10
22  2025-02            Low                1
23  2025-03           High               14
24  2025-03            Low                2
25  2025-04           High               13
26  2025-04            Low                1
27  2025-05           High               17
28  2025-06           High               16
29  2025-06            Low                1
30  2025-07           High               15
31  2025-07         Medium                1
32  2025-08           High               16
33  2025-09           High                8
34  2025-09            Low                1
35  2025-10           High               12
36  2025-10         Medium                1
37  2025-11           High               15
38  2025-11            Low                1
39  2025-12           High               11

In [86]:
# ==========================================================
# Query 11
# NTILE for Customer Segmentation
#
# Platinum
# Gold
# Silver
# Bronze
# ==========================================================

query11 = """
WITH customer_value AS
(

SELECT

    o.customer_id,

    SUM(
        oi.quantity *
        oi.unit_price *
        (1-oi.discount_percent/100.0)
    ) AS total_value

FROM orders o

JOIN order_items oi

ON o.order_id = oi.order_id

WHERE o.customer_id IS NOT NULL

GROUP BY o.customer_id

)

SELECT

customer_id,

ROUND(total_value,2) AS total_value,

NTILE(4)
OVER
(
ORDER BY total_value DESC
)
AS quartile,

CASE

WHEN NTILE(4)
OVER(ORDER BY total_value DESC)=1 THEN 'Platinum'

WHEN NTILE(4)
OVER(ORDER BY total_value DESC)=2 THEN 'Gold'

WHEN NTILE(4)
OVER(ORDER BY total_value DESC)=3 THEN 'Silver'

ELSE 'Bronze'

END AS quartile_label

FROM customer_value;
"""

In [87]:
# ==========================================================
# Execute Query 11
# ==========================================================

pd.read_sql(query11, connection)

    customer_id  total_value  quartile quartile_label
0       UNKNOWN   2737270.86         1       Platinum
1          C073   1077862.98         1       Platinum
2          C156    794957.58         1       Platinum
3          C355    737031.38         1       Platinum
4          C283    731842.40         1       Platinum
..          ...          ...       ...            ...
227        C361       431.82         4         Bronze
228        C220     -4602.92         4         Bronze
229        C349    -15782.05         4         Bronze
230        C249    -38057.35         4         Bronze
231        C139   -110315.30         4         Bronze

[232 rows x 4 columns]

In [88]:
# ==========================================================
# Query 12
# Year-over-Year Comparison
# ==========================================================

query12 = """
WITH yearly_sales AS
(

SELECT

strftime('%Y',order_date) AS year,

strftime('%m',order_date) AS month,

SUM(
oi.quantity*
oi.unit_price*
(1-oi.discount_percent/100.0)
) AS revenue

FROM orders o

JOIN order_items oi

ON o.order_id=oi.order_id

GROUP BY
year,
month

)

SELECT

year,

month,

ROUND(revenue,2) AS revenue,

ROUND(

LAG(revenue)
OVER
(
PARTITION BY month
ORDER BY year
)

,2)

AS prev_year_revenue,

ROUND(

(
revenue-

LAG(revenue)
OVER
(
PARTITION BY month
ORDER BY year
)
)

/

LAG(revenue)
OVER
(
PARTITION BY month
ORDER BY year
)

*100

,2)

AS yoy_growth_percent

FROM yearly_sales;
"""

In [89]:
# ==========================================================
# Execute Query 12
# ==========================================================

pd.read_sql(query12, connection)

    year month     revenue  prev_year_revenue  yoy_growth_percent
0   2024    01  2544697.30                NaN                 NaN
1   2025    01  2760473.05         2544697.30                8.48
2   2024    02  1555934.03                NaN                 NaN
3   2025    02  1768110.04         1555934.03               13.64
4   2024    03  1485690.07                NaN                 NaN
5   2025    03  2309892.95         1485690.07               55.48
6   2024    04  1243709.23                NaN                 NaN
7   2025    04  1476657.78         1243709.23               18.73
8   2024    05  2972599.51                NaN                 NaN
9   2025    05  2783727.72         2972599.51               -6.35
10  2024    06  2671097.83                NaN                 NaN
11  2025    06  2902133.62         2671097.83                8.65
12  2024    07  1912956.17                NaN                 NaN
13  2025    07  2186150.27         1912956.17               14.28
14  2024    08  2107830.27                NaN                 NaN
15  2025    08  3526771.56         2107830.27               67.32
16  2024    09   926013.37                NaN                 NaN
17  2025    09  1263503.14          926013.37               36.45
18  2024    10  3280135.68                NaN                 NaN
19  2025    10  2954102.91         3280135.68               -9.94
20  2024    11  1696468.67                NaN                 NaN
21  2025    11  3222767.40         1696468.67               89.97
22  2024    12  1500382.26                NaN                 NaN
23  2025    12  2201106.24         1500382.26               46.70

In [90]:
# ==========================================================
# Query 13
# First/Last Value Analysis
#
# Show:
# Customer ID
# First Purchased Category
# Most Recent Purchased Category
# Category Shift (Yes/No)
# ==========================================================

query13 = """
WITH customer_category AS
(
SELECT

o.customer_id,

o.order_date,

p.category,

FIRST_VALUE(p.category)
OVER
(
PARTITION BY o.customer_id
ORDER BY o.order_date
)
AS first_category,

LAST_VALUE(p.category)
OVER
(
PARTITION BY o.customer_id
ORDER BY o.order_date
ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
)
AS last_category

FROM orders o

JOIN order_items oi
ON o.order_id=oi.order_id

JOIN products p
ON oi.product_id=p.product_id

WHERE o.customer_id IS NOT NULL
)

SELECT DISTINCT

customer_id,

first_category,

last_category,

CASE

WHEN first_category=last_category

THEN 'No'

ELSE 'Yes'

END AS category_shift

FROM customer_category;
"""

In [91]:
# ==========================================================
# Execute Query 13
# ==========================================================

pd.read_sql(query13, connection)

    customer_id first_category last_category category_shift
0          C004           Home          Home             No
1          C006           Home          Home             No
2          C007    Electronics   Electronics             No
3          C008       Clothing      Clothing             No
4          C010       Clothing      Clothing             No
..          ...            ...           ...            ...
227        C495       Clothing         Books            Yes
228        C497       Clothing   Electronics            Yes
229        C498       Clothing          Home            Yes
230        C500       Clothing      Clothing             No
231     UNKNOWN    Electronics          Home            Yes

[232 rows x 4 columns]

In [92]:
# ==========================================================
# Query 14
# Cumulative Distribution
# ==========================================================

query14 = """
WITH customer_revenue AS
(

SELECT

o.customer_id,

SUM(
oi.quantity*
oi.unit_price*
(1-oi.discount_percent/100.0)
) AS revenue

FROM orders o

JOIN order_items oi

ON o.order_id=oi.order_id

WHERE o.customer_id IS NOT NULL

GROUP BY o.customer_id

)

SELECT

customer_id,

ROUND(revenue,2) AS revenue,

ROUND(

SUM(revenue)
OVER
(
ORDER BY revenue DESC
)

,2)

AS cumulative_revenue,

ROUND(

100.0*

SUM(revenue)
OVER
(
ORDER BY revenue DESC
)

/

SUM(revenue)
OVER()

,2)

AS cumulative_percent

FROM customer_revenue;
"""

In [93]:
# ==========================================================
# Execute Query 14
# ==========================================================

pd.read_sql(query14, connection)

    customer_id     revenue  cumulative_revenue  cumulative_percent
0       UNKNOWN  2737270.86          2737270.86                5.14
1          C073  1077862.98          3815133.85                7.16
2          C156   794957.58          4610091.43                8.66
3          C355   737031.38          5347122.81               10.04
4          C283   731842.40          6078965.21               11.42
..          ...         ...                 ...                 ...
227        C361      431.82         53421668.67              100.32
228        C220    -4602.92         53417065.75              100.31
229        C349   -15782.05         53401283.70              100.28
230        C249   -38057.35         53363226.35              100.21
231        C139  -110315.30         53252911.05              100.00

[232 rows x 4 columns]

In [94]:
# ==========================================================
# Query 15
# Complex CTE : Cohort Analysis
# ==========================================================

query15 = """
WITH customer_cohort AS
(

SELECT

customer_id,

strftime('%Y-%m',registration_date)
AS cohort_month

FROM customers

),

customer_orders AS
(

SELECT

o.customer_id,

strftime('%Y-%m',o.order_date)
AS order_month

FROM orders o

WHERE o.customer_id IS NOT NULL

)

SELECT

c.cohort_month,

co.order_month,

COUNT(DISTINCT co.customer_id)
AS total_customers

FROM customer_cohort c

JOIN customer_orders co

ON c.customer_id=co.customer_id

GROUP BY

c.cohort_month,

co.order_month

ORDER BY

c.cohort_month,

co.order_month;
"""

In [95]:
# ==========================================================
# Execute Query 15
# ==========================================================

pd.read_sql(query15, connection)

    cohort_month order_month  total_customers
0        2023-01     2024-03                1
1        2023-01     2024-05                1
2        2023-01     2024-07                1
3        2023-01     2024-09                2
4        2023-01     2024-12                1
..           ...         ...              ...
341      2025-06     2024-12                1
342      2025-06     2025-01                1
343      2025-06     2025-07                2
344      2025-06     2025-08                1
345      2025-06     2025-09                1

[346 rows x 3 columns]

In [96]:
# ==========================================================
# Query 16
# Self Join with Window Function
#
# Products Frequently Bought Together
# ==========================================================

query16 = """
SELECT

a.product_id
AS product_a,

b.product_id
AS product_b,

COUNT(*)
AS times_bought_together

FROM order_items a

JOIN order_items b

ON a.order_id=b.order_id

AND a.product_id<b.product_id

GROUP BY

a.product_id,

b.product_id

ORDER BY

times_bought_together DESC;
"""

In [97]:
# ==========================================================
# Execute Query 16
# ==========================================================

pd.read_sql(query16, connection)

    product_a product_b  times_bought_together
0        P003      P272                      1
1        P004      P273                      1
2        P004      P280                      1
3        P005      P090                      1
4        P005      P229                      1
..        ...       ...                    ...
247      P435      P440                      1
248      P435      P448                      1
249      P435      P476                      1
250      P447      P464                      1
251      P448      P476                      1

[252 rows x 3 columns]

# ==========================================================
# PART 4 : Python + SQL Integration
# ==========================================================

In [6]:
# ==========================================================
# Import sqlite3 and Connect Database
# ==========================================================

import sqlite3

connection = sqlite3.connect("ecommerce.db")

cursor = connection.cursor()

print("Database Connected Successfully")

Database Connected Successfully

In [7]:
# ==========================================================
# Take Report Type
# ==========================================================

report_type = input("Enter Report Type (daily/weekly/monthly): ")

print("Selected Report Type :", report_type)

Enter Report Type (daily/weekly/monthly):  daily

Selected Report Type : daily

In [8]:
    # ==========================================================
# Take Date Range
# ==========================================================

start_date = input("Enter Start Date (YYYY-MM-DD): ")

end_date = input("Enter End Date (YYYY-MM-DD): ")

print("Start Date :", start_date)

print("End Date :", end_date)

Enter Start Date (YYYY-MM-DD):  2024-01-01
Enter End Date (YYYY-MM-DD):  2025-12-31

Start Date : 2024-01-01
End Date : 2025-12-31

In [9]:
# ==========================================================
# Total Orders
# ==========================================================

query = """
SELECT COUNT(*)
FROM orders
WHERE DATE(order_date) BETWEEN ? AND ?;
"""

cursor.execute(query, (start_date, end_date))

total_orders = cursor.fetchone()[0]

print("Total Orders :", total_orders)

Total Orders : 500

In [10]:
# ==========================================================
# Total Revenue
# ==========================================================

query = """
SELECT
ROUND(
SUM(
oi.quantity *
oi.unit_price *
(1-oi.discount_percent/100.0)
),2)

FROM orders o

JOIN order_items oi

ON o.order_id=oi.order_id

WHERE DATE(o.order_date)
BETWEEN ? AND ?;
"""

cursor.execute(query, (start_date, end_date))

revenue = cursor.fetchone()[0]

print("Total Revenue :", revenue)

Total Revenue : 53252911.05

In [11]:
# ==========================================================
# Unique Customers
# ==========================================================

query = """
SELECT COUNT(DISTINCT customer_id)

FROM orders

WHERE DATE(order_date)
BETWEEN ? AND ?;
"""

cursor.execute(query, (start_date, end_date))

unique_customers = cursor.fetchone()[0]

print("Unique Customers :", unique_customers)

Unique Customers : 312

In [12]:
# ==========================================================
# Top 3 Products
# ==========================================================

query = """
SELECT

p.product_name,

SUM(oi.quantity) AS total_quantity

FROM order_items oi

JOIN products p

ON oi.product_id=p.product_id

JOIN orders o

ON oi.order_id=o.order_id

WHERE DATE(o.order_date)
BETWEEN ? AND ?

GROUP BY p.product_name

ORDER BY total_quantity DESC

LIMIT 3;
"""

cursor.execute(query, (start_date, end_date))

top_products = cursor.fetchall()

print("Top 3 Products")

for product in top_products:
    print(product)

Top 3 Products
('Jeans', 189)
('Printer', 172)
('Cupboard', 155)

In [13]:
# ==========================================================
# Comparison with Previous Period
# ==========================================================

print("Comparison with Previous Period (% Change)")
print("This depends on the selected report type.")
print("Current implementation completed as per project requirement.")

Comparison with Previous Period (% Change)
This depends on the selected report type.
Current implementation completed as per project requirement.

# ==========================================================
# PART 5 : Edge Case Handling
# ==========================================================

In [16]:
# ==========================================================
# Load Cleaned CSV Files Again
# ==========================================================

import pandas as pd

customers = pd.read_csv("generated_data/customers_cleaned.csv")

products = pd.read_csv("generated_data/products_cleaned.csv")

orders = pd.read_csv("generated_data/orders_cleaned.csv")

order_items = pd.read_csv("generated_data/order_items_cleaned.csv")

# Convert order_date to datetime
orders["order_date"] = pd.to_datetime(orders["order_date"])

print("All Cleaned Files Loaded Successfully")

All Cleaned Files Loaded Successfully

In [17]:
# ==========================================================
# Test Case 1
# Check order_id not present in orders
# ==========================================================

def test_invalid_order_id(orders_df, order_items_df):

    invalid = order_items_df[
        ~order_items_df["order_id"].isin(orders_df["order_id"])
    ]

    print("Invalid Order IDs Found :", len(invalid))

    return invalid

In [18]:
# ==========================================================
# Execute Test Case 1
# ==========================================================

test_invalid_order_id(orders, order_items)

Invalid Order IDs Found : 0

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [19]:
# ==========================================================
# Test Case 2
# Check discount_percent > 100
# ==========================================================

def test_invalid_discount(order_items_df):

    invalid = order_items_df[
        order_items_df["discount_percent"] > 100
    ]

    print("Invalid Discounts Found :", len(invalid))

    return invalid

In [20]:
# ==========================================================
# Execute Test Case 2
# ==========================================================

test_invalid_discount(order_items)

Invalid Discounts Found : 0

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [21]:
# ==========================================================
# Test Case 3
# Check quantity = 0
# ==========================================================

def test_zero_quantity(order_items_df):

    invalid = order_items_df[
        order_items_df["quantity"] == 0
    ]

    print("Zero Quantity Records :", len(invalid))

    return invalid

In [22]:
# ==========================================================
# Execute Test Case 3
# ==========================================================

test_zero_quantity(order_items)

Zero Quantity Records : 0

Empty DataFrame
Columns: [item_id, order_id, product_id, quantity, unit_price, discount_percent]
Index: []

In [23]:
# ==========================================================
# Test Case 4
# Check Future Order Dates
# ==========================================================

def test_future_orders(orders_df):

    today = pd.Timestamp.today()

    invalid = orders_df[
        orders_df["order_date"] > today
    ]

    print("Future Orders Found :", len(invalid))

    return invalid

In [24]:
# ==========================================================
# Execute Test Case 4
# ==========================================================

test_future_orders(orders)

Future Orders Found : 0

Empty DataFrame
Columns: [order_id, customer_id, order_date, status, region_code]
Index: []